### ISSUE TITLE
creating example for solving MIP

### ISSUE THREAD

**Issue by marekyggdrasil** [hgourvest/node-glpk#2]
Inspired by the example

https://github.com/hgourvest/node-glpk/blob/master/examples/sample.js

and also by the C version of MIP solver

https://gist.github.com/msakai/2450935

I wanted to create (and pull request to your project) an example that solves a mixed-integer problem. I chosen a standard TSP (however initially I intentionally skipped enforcing a Hamiltonian cycle so that solution would be easier to evaluate in terms of correctness).

https://gist.github.com/marekyggdrasil/9808ee850ffc5a1e61a9cc028f943767

GLPK claims solution is optimal, however at same time infeasible. From my understanding it is opposite, it is feasible however not optimal.

**Comment by hgourvest** [comment]
The same variable can't have 2 different values at same time, only in a quantic universe :)

console.log('feasible:', lp.mipStatus() == glp.FEAS);
console.log('optimal:', lp.mipStatus() == glp.OPT);

**Comment by marekyggdrasil** [comment]
`lp.mipStatus()` is an integer, you need to compare it to something to know how to interpret the value, I don't expect it to have both of those values at same time, I just test one by one.

Any advises on my issue? It is _not_ resolved.

```
z = 0 * x_1_1 + 1 * x_1_2 + 1 * x_1_3 + 1 * x_1_4 + 1 * x_1_5 + 1 * x_2_1 + 0 * x_2_2 + 1 * x_2_3 + 1 * x_2_4 + 1 * x_2_5 + 1 * x_3_1 + 1 * x_3_2 + 0 * x_3_3 + 1 * x_3_4 + 1 * x_3_5 + 1 * x_4_1 + 1 * x_4_2 + 1 * x_4_3 + 0 * x_4_4 + 1 * x_4_5 + 1 * x_5_1 + 1 * x_5_2 + 1 * x_5_3 + 1 * x_5_4 + 0 * x_5_5

(1): x_1_1 + x_1_2 + x_1_3 + x_1_4 + x_1_5 = 1.0
(2): x_2_1 + x_2_2 + x_2_3 + x_2_4 + x_2_5 = 1.0
(3): x_3_1 + x_3_2 + x_3_3 + x_3_4 + x_3_5 = 1.0
(4): x_4_1 + x_4_2 + x_4_3 + x_4_4 + x_4_5 = 1.0
(5): x_5_1 + x_5_2 + x_5_3 + x_5_4 + x_5_5 = 1.0
(6): x_1_1 + x_2_1 + x_3_1 + x_4_1 + x_5_1 = 1.0
(7): x_1_2 + x_2_2 + x_3_2 + x_4_2 + x_5_2 = 1.0
(8): x_1_3 + x_2_3 + x_3_3 + x_4_3 + x_5_3 = 1.0
(9): x_1_4 + x_2_4 + x_3_4 + x_4_4 + x_5_4 = 1.0
(10): x_1_5 + x_2_5 + x_3_5 + x_4_5 + x_5_5 = 1.0
```

Optimal for this should be

```
z = 0
x_1_1 = 1
x_2_2 = 1
x_3_3 = 1
x_4_4 = 1
x_5_5 = 1
(rest = 0)
```

However GLPK finds

```
z = 2
x_1_4 = 1
x_2_2 = 1
x_3_3 = 1
x_4_1 = 1
x_5_5 = 1
(rest = 0)
```

I suspect that it solves the linear relaxation and finds all continuous variables become integers and then just stops.
If I add another constraint to enforce `z < 2` problem has no solution.

**Comment by hgourvest** [comment]
You have to use a callback to examine the intermediate status of the solver.

```
function callback(tree){
    switch (lp.mipStatus()) {
        case glp.FEAS:
            console.log(">>> FEASIBLE");
            break;
        default:

    }
}

lp.intopt({cbFunc: callback}, function(err) {
```

**Comment by hgourvest** [comment]
from glpk documentation:

> Constraint coefficients (elements of the constraint matrix) should be specified as triplets (ia[k], ja[k], ar[k]) for k = **1**,...,ne, where ia[k] is the row index, ja[k] is the column index, and ar[k] is a numeric value of corresponding constraint coefficient. The parameter ne specifies the total number of (non-zero) elements in the matrix to be loaded. Coefficients with identical indices are not allowed. Zero coefficients are allowed, however, they are not stored in the constraint matrix.

You have to declare arrays with length +1, and ignore value at index 0.

```
var ia = new Int32Array(rules.length+1);
var ja = new Int32Array(rules.length+1);
var ar = new Float64Array(rules.length+1);

for (var k = 1; k <= rules.length; k++) {
    var rule = rules[k-1];
    ia[k] = rule[0], ja[k] = rule[1], ar[k] = 1.0;
}

lp.loadMatrix(rules.length, ia, ja, ar);
```
