### ISSUE TITLE
How do we set MIP time limit or optimality gap to stop in .js file?

### ISSUE THREAD

**Issue by ekinkoker** [hgourvest/node-glpk#3]
Hi,

I am using Node.js version of GLPK by adjusting the example mathprog.js file. I just replace the .mod file name with my own model file to solve my problems. The issue is, it takes too long to solve one of my MIP and I am fine with a near-optimal solution. So the question is, is there a way to set a MIP time limit or change the optimality gap to stop from the .js file? Thank you!

**Comment by hgourvest** [comment]
in the callback method, you can get the gap with tree.mipGap() and stop searching with tree.terminate(), lp.intopt(...) should return with glp.ESTOP.

**Comment by ekinkoker** [comment]
Awesome, thank you so much!
