### ISSUE TITLE
Error when installed under Node 9 and Node 10

### ISSUE THREAD

**Issue by DmitryMyadzelets** [hgourvest/node-glpk#6]
```cc
In file included from ../src/tree.hpp:5,
                 from ../src/nodeglpk.cc:3:
../src/nodeglpk.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../src/common.h:41:11: error: ‘class v8::Object’ has no member named ‘ForceSet’
 (target)->ForceSet(constant_name, constant_value, constant_attributes);\
           ^~~~~~~~
```
The issure occures due to deprecation of  the method`Nan::ForceSet` in the [nan version 2.8.0 Nov 15 2017](https://github.com/nodejs/nan/blob/master/CHANGELOG.md#280-nov-15-2017)

**Comment by DmitryMyadzelets** [comment]
For those who have skills to solve this issue these links might be usfull:
- [Stuff V8 will be breaking soon](https://github.com/nodejs/nan/issues/504)
- [A patch which solves similar issue](https://github.com/DreamLab/node-uriparser/commit/0f017fcb3065f9748a2d0383bc810100019de914)

**Comment by DmitryMyadzelets** [comment]
So, the `glpk@0.0.12` can be installed under Node's version higher then 8. I've got it working under `nodejs 8.17.0` only.

Below is a how you can install the obsolete version of node on Debian:
```bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install nodejs=8*
````

**Comment by hgourvest** [comment]
Thanks Dmitry!

**Comment by DmitryMyadzelets** [comment]
Please, push the package to `npm`.
